[package]
name = "io-reactor"
description = "Rust implementation of reactor pattern for I/O resources"
version = "0.1.0"
edition = "2021"

[lib]
name = "reactor"

[dependencies]
amplify = "4.0.0-beta.1"
crossbeam-channel = "0.5.6"
popol = { version = "1.0.0", git = "https://github.com/Cyphernet-WG/popol", branch = "api", optional = true }
polling = { version = "2.4.0", optional = true }
epoll = { version = "4.3.1", optional = true }
mio = { version = "0.8.5", optional = true }
zmq = { version = "0.10.0", optional = true }
socket2 = { version = "0.4.7", optional = true }
log = { version = "0.4.17", optional = true }
libc = "0.2.71"

[features]
default = ["popol", "socket2"]
all = ["popol", "polling", "epoll", "mio", "zmq", "socket2", "log"]
